// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBzaESnRzm8wmmMniTGwQsNd9T5cdT507s',
    appId: '1:755522049248:web:2f129628fa465b9f962c85',
    messagingSenderId: '755522049248',
    projectId: 'expense-tracker-app-97ddd',
    authDomain: 'expense-tracker-app-97ddd.firebaseapp.com',
    storageBucket: 'expense-tracker-app-97ddd.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD2ZYS_LZ86qaRanXGSvXct5OffP8lq758',
    appId: '1:755522049248:android:0eefae8336c719b1962c85',
    messagingSenderId: '755522049248',
    projectId: 'expense-tracker-app-97ddd',
    storageBucket: 'expense-tracker-app-97ddd.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC_FPUp594FAdr04a_pzomOHGLnfG0uivM',
    appId: '1:755522049248:ios:ac91f49ec48d0bbe962c85',
    messagingSenderId: '755522049248',
    projectId: 'expense-tracker-app-97ddd',
    storageBucket: 'expense-tracker-app-97ddd.appspot.com',
    iosBundleId: 'com.example.expenseTrackerApp',
  );
}
